import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Container } from "../components/Container/index";
import { Header } from "../components/Header/index";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: {
        default: "The Abel Blog",
        template: "%s | The Abel Blog"
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Container>
                    <Header />

                    {children}

                    <footer>
                        <p className="text-6xl font-bold text-center py-8">
                            Aqui é o Footer
                        </p>
                    </footer>
                </Container>
            </body>
        </html>
    );
}
